# _config.yml
title: "Faye Voulivasi"
description: "Applied ML · Ranking & Personalization · Scalable Decision Systems"
theme: jekyll-theme-slate

# Project site settings 
url: "https://rosevoul.github.io"
baseurl: "/ml-systems"

markdown: kramdown
kramdown:
  input: GFM

plugins: []
